[versions]
champeau-jmh = "0.7.2"
gson = "2.11.0"
jmh = "1.37"
kotlin = "2.1.0"
kotlinx-serialization = "1.7.3"
shadow = "8.3.5"

[plugins]
champeau-jmh = { id = "me.champeau.jmh", version.ref = "champeau-jmh" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }